name: nest
description: |
  Example component that includes a Nest.js backend and a mysql database.
keywords:
  - typescript
  - nest.js
  - mysql

interfaces:
  api:
    url: ${{ services.api.interfaces.main.url }}
    ingress:
      subdomain: api

secrets:
  api_db_host:
    description: API database host override
    required: false
  api_db_name:
    description: Name of the database used by the API
    default: test_database
  root_db_user:
    description: Root user to assign to the generated database
    default: root
  root_db_pass:
    description: Root password to assign to the generated database
    default: architect

services:
  api-db:
    image: mariadb:latest
    interfaces:
      mysql:
        host: ${{ secrets.api_db_host }}
        port: 3306
        username: ${{ secrets.root_db_user }}
        password: ${{ secrets.root_db_pass }}
        protocol: mysql
        path: /${{ secrets.api_db_name }}
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.root_db_pass }}
      MYSQL_DATABASE: ${{ secrets.api_db_name }}

  api:
    depends_on:
      - api-db
    build:
      context: ./backend
      args:
        NODE_ENV: production
    interfaces:
      main: &api-port 3000
    # liveness_probe:
    #   command: curl --fail localhost:3000/users || exit 1
    #   interval: 30s
    #   failure_threshold: 3
    environment:
      PORT: *api-port
      DB_ADDR: ${{ services.api-db.interfaces.mysql.url }}
    ${{ if architect.environment == 'local' }}:
      command: npm run start:debug
      volumes:
        src:
          mount_path: /usr/src/app/src
          host_path: ./backend/src
