name: nestjs
description: Example component that includes a Nest.js and a postgres database.
keywords:
  - architect
  - typescript
  - nest.js
  - postgres

secrets:
  db_user:
    description: Root user to assign to the component's database
    default: architect
  db_pass:
    description: Root password to assign to the component's database
    default: secret
  db_name:
    description: Name of the database the component will store content in
    default: api-db
  db_port:
    description: Port for the database
    default: 5432
  subdomain:
    description: The subdomain to expose the application on
    default: nestjs

services:
  app:
    build:
      context: .
    interfaces:
      main:
        port: 3000
        ingress:
          subdomain: ${{ secrets.subdomain }}
    # The liveness_probe makes sure the application is healthy - if not, it will re-start the application
    liveness_probe:
      command: curl --fail localhost:3000
      interval: 30s
      failure_threshold: 3
      initial_delay: 10s
    environment:
      PORT: 3000
      DB_URL: ${{ services.api-db.interfaces.main.url }}
    # Debug block is used to enable hot-reloading to make real-time changes to an
    #   application while running `architect dev`. For more info, see -
    #   https://docs.architect.io/components/local-configuration/#hot-reloading
    debug:
      command: npm run start:debug
      volumes:
        src:
          mount_path: /usr/src/app/src
          host_path: ./src
        public:
          mount_path: /usr/src/app/public
          host_path: ./public
        views:
          mount_path: /usr/src/app/views
          host_path: ./views

  api-db:
    image: postgres:14
    interfaces:
      main:
        port: ${{ secrets.db_port }}
        protocol: postgresql
        username: ${{ secrets.db_user }}
        password: ${{ secrets.db_pass }}
        path: /${{ secrets.db_name }}
    environment:
      POSTGRES_USER: ${{ secrets.db_user }}
      POSTGRES_PASSWORD: ${{ secrets.db_pass }}
      POSTGRES_DB: ${{ secrets.db_name }}
