name: nestjs
description: |
  Example component that includes a Nest.js backend and a mysql database.
keywords:
  - typescript
  - nest.js
  - mysql

secrets:
  api_db_host:
    description: API database host override
    required: false
  api_db_name:
    description: Name of the database used by the API
    default: test_database
  root_db_user:
    description: Root user to assign to the generated database
    default: root
  root_db_pass:
    description: Root password to assign to the generated database
    default: architect
  api_port:
    description: Port for api
    default: 3000

services:
  api-db:
    image: mariadb:latest
    interfaces:
      database:
        host: ${{ secrets.api_db_host }}
        port: 3306
        username: ${{ secrets.root_db_user }}
        password: ${{ secrets.root_db_pass }}
        protocol: mysql
        path: /${{ secrets.api_db_name }}
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.root_db_pass }}
      MYSQL_DATABASE: ${{ secrets.api_db_name }}

  api:
    depends_on:
      - api-db
    build:
      context: ./backend
      args:
        NODE_ENV: production
    interfaces:
      http: ${{ secrets.api_port }}
    liveness_probe:
      command: curl --fail localhost:3000/items
      interval: 30s
      failure_threshold: 3
    environment:
      PORT: ${{ secrets.api_port }}
      DB_ADDR: ${{ services.api-db.interfaces.database.url }}
    debug:
      command: npm run start:debug
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          mount_path: /usr/src/app/src
          host_path: ./backend/src

interfaces:
  api:
    description: A description
    url: ${{ services.api.interfaces.http.url }}
    ingress:
      subdomain: api